### ISSUE TITLE
TypeError when using react-syntax-highlighter

### ISSUE THREAD

**Issue by lonkaars** [remarkjs/react-markdown#570]
### Subject of the issue

I get this error when I try to use react-syntax-highlighter with react-markdown:

```
TypeError: Cannot read property 'children' of undefined
    at mergeNodeChildren (.../node_modules/react-markdown/lib/ast-to-react.js:246:16)
    at getNodeProps (.../node_modules/react-markdown/lib/ast-to-react.js:206:40)
    at astToReact (.../node_modules/react-markdown/lib/ast-to-react.js:37:19)
    at .../node_modules/react-markdown/lib/ast-to-react.js:42:14
    at Array.map (<anonymous>)
    at resolveChildren (.../node_modules/react-markdown/lib/ast-to-react.js:41:43)
    at astToReact (.../node_modules/react-markdown/lib/ast-to-react.js:38:73)
    at .../node_modules/react-markdown/lib/react-markdown.js:48:12
    at Array.forEach (<anonymous>)
    at ReactMarkdown (.../node_modules/react-markdown/lib/react-markdown.js:47:40)
    at ReactMarkdownWithHtml (.../node_modules/react-markdown/lib/with-html.js:13:10)
    at processChild (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (.../node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
```

It looks like an internal react-markdown error so I figured this is the right place to submit this issue

### Your environment

*   **OS**: Arch Linux (kernel 5.11.13)
*   **Packages**:
    typescript@4.2.3
    react-markdown@5.0.3
    react-syntax-highlighter@15.4.3
    next@10.0.9
    react@17.0.2
*   **Env**: Node 15.14.0, yarn 1.22.10, Brave (chromium) 89.0.4389.114

### Steps to reproduce

```tsx
import gfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';

export function RenderedArticle(props: { content: string; }) {
	return <ReactMarkdownWithHTML
		plugins={[gfm]}
		allowDangerousHtml
		children={props.content}
		renderers={{
			code: (props: {
				language: string;
				value: ReactNode;
			}) {
				return <SyntaxHighlighter language={props.language} children={props.value}/>;
			}
		}}
	/>;
}
```

### Expected behavior

The code should compile fine and display beautiful highlighted code :sparkles:

### Actual behavior

TypeError: Cannot read property 'children' of undefined :(

**Comment by wooorm** [comment]
What text are you passing?

**Comment by lonkaars** [comment]
I tried `console.log()`ing the props, but they're both undefined inside the custom `code` renderer. The input should be:
```
```py
# api/tests/example.py
from flask import Blueprint

example = Blueprint('example', __name__)

@example.route('/example')
def index():
	# python dictionaries are automatically converted to JSON by flask
    return {"hello": "world"}, 200 # flask returns http code 200 by default if no code is explicitly defined

# define a `dynamic_route` variable at the end of your endpoint definition file
# dynamic_route[0] is the namespace
# dynamic_route[1] is your flask.Blueprint
dynamic_route = ["/tests", status]

# this endpoint will be routed to /tests/example
#                                  \___/ \_____/
#                                    |      |
#                                    |      endpoint (defined by the @Blueprint.route() decorator)
#                                    |
#                                    namespace (defined in dynamic_route variable)
\```
```

I don't think this has anything to do with props being redefined inside the code renderer, because it's also undefined when the code renderer is moved to a seperate function. I've also tried calling the `<SyntaxRenderer>` component directly with the same results.

**Comment by wooorm** [comment]
Probably the old broken HTML parser. So this should be fixed by https://github.com/remarkjs/react-markdown/pull/563, which’ll land soon

**Comment by lonkaars** [comment]
Thanks! Is there any way I could update to the new html parser? I read about a new upcoming release in the readme, but can I just `yarn update react-markdown --latest`, or are there more steps involved?

**Comment by wooorm** [comment]
Going to release it today/tomorrow or so. First have to think if there should be some more things landing with it

**Comment by wooorm** [comment]
Released!

**Comment by jahirfiquitiva** [comment]
@lonkaars @wooorm

Would you mind helping me to fix this? I started using React Syntax Highlighter and now the inline code looks like this:

<img width="939" alt="Shot 2021-04-15 at 03-28-41@2x" src="https://user-images.githubusercontent.com/10360816/114839009-e6f0d780-9d9a-11eb-8885-b2e4fad34d7b.png">

But I was expecting it to look like this
<img width="377" alt="Shot 2021-04-15 at 03-29-02@2x" src="https://user-images.githubusercontent.com/10360816/114839055-f1ab6c80-9d9a-11eb-8fd7-3a5289a53812.png">

Here's the code snippets:
```typescript
const CodeRenderer = (props: any) => {
  return <SyntaxHighlighter language={props.language} style={dracula}>
    {props.children}
  </SyntaxHighlighter>;
};
```

```typescript
<ReactMarkdown
          plugins={[gfm]}
          components={{
            // @ts-ignore
            // eslint-disable-next-line react/display-name
            heading: ({ node, ...props }) => <HeadingRenderer {...props} />,
            // @ts-ignore
            // eslint-disable-next-line react/display-name
            code: ({ node, ...props }) => <CodeRenderer {...props} />,
          }}>
          {mdBody}
        </ReactMarkdown>
```

**Comment by wooorm** [comment]
Please see the readme, it has examples: https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight

**Comment by jahirfiquitiva** [comment]
@wooorm

I'm seeing this error with the code in the example
```gradle
/Users/jahir/dev/jahir/web/node_modules/react-syntax-highlighter/dist/esm/styles/prism/index.js:1
export { default as coy } from './coy';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack-internal:///react-syntax-highlighter/dist/esm/styles/prism:1:18)
    at Object.react-syntax-highlighter/dist/esm/styles/prism (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:1075:1)
    at __webpack_require__ (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:29:31)
    at eval (webpack-internal:///./components/blog/single-post/post.tsx:14:104)
    at Module../components/blog/single-post/post.tsx (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:227:1)
    at __webpack_require__ (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:29:31)
    at eval (webpack-internal:///./pages/blog/[postname].tsx:16:91)
    at Module../pages/blog/[postname].tsx (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:777:1)
    at __webpack_require__ (/Users/jahir/dev/jahir/web/.next/server/pages/blog/[postname].js:29:31)
```

**Comment by wooorm** [comment]
You are using ESM files but your project is not set up to support ESM. Please defer to `react-syntax-highlighter` for how to use that project.

**Comment by lonkaars** [comment]
Could this conversation be moved to another issue, I don't see how it's related to my original problem. Thanks!

**Comment by shuent** [comment]
> @lonkaars @wooorm
> 
> Would you mind helping me to fix this? I started using React Syntax Highlighter and now the inline code looks like this:
> 
> <img alt="Shot 2021-04-15 at 03-28-41@2x" width="939" src="https://user-images.githubusercontent.com/10360816/114839009-e6f0d780-9d9a-11eb-8885-b2e4fad34d7b.png">
> 
> But I was expecting it to look like this
> <img alt="Shot 2021-04-15 at 03-29-02@2x" width="377" src="https://user-images.githubusercontent.com/10360816/114839055-f1ab6c80-9d9a-11eb-8fd7-3a5289a53812.png">
> 
> Here's the code snippets:
> 
> ```ts
> const CodeRenderer = (props: any) => {
>   return <SyntaxHighlighter language={props.language} style={dracula}>
>     {props.children}
>   </SyntaxHighlighter>;
> };
> ```
> 
> ```ts
> <ReactMarkdown
>   plugins={[gfm]}
>   components={{
>     // @ts-ignore
>     // eslint-disable-next-line react/display-name
>     code: ({ node, ...props }) => <CodeRenderer {...props} />,
>   }}>
>   {mdBody}
> </ReactMarkdown>
> ```

same bug using in Next.js.

**Comment by SalahAdDin** [comment]
Well, it is not solved for me:
```
~~~ts
import "@capacitor-community/uxcam"
import { Plugins } from "@capacitor/core"
import { LogEventProperty, UserProperty } from "@capacitor-community/uxcam"
import { appEnv } from "../env"
~~~

```

Never gets syntax higlighted but ever shows a `code` tag, why?

**Comment by ChristianMurphy** [comment]
@SalahAdDin  https://github.com/remarkjs/react-markdown/issues/570#issuecomment-820235949 and https://github.com/remarkjs/react-markdown#use-custom-components-syntax-highlight
Explain how to add syntax highlighting.
If you have a futher question the discussion forum would be a better venue https://github.com/remarkjs/remark/discussions
