### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by zjjjjjjjjjjd** [remarkjs/react-markdown#649]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.1

### Steps to reproduce

```
import React from 'react'
import RM from 'react-markdown'

const ReactMarkdown = () => {
  return (
    <div>
      <RM># This is a header\n\nAnd this is a paragraph</RM>
    </div>
  )
}

export default ReactMarkdown
```
in ssr project
### Expected behavior

maybe right

### Actual behavior

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\work\develop-smart-campus\node_modules\react-markdown\index.js
require() of ES modules is not supported.
require() of D:\work\develop-smart-campus\node_modules\react-markdown\index.js from D:\work\develop-smart-campus\node_modules\@leke\ssr\build\devServer.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\work\develop-smart-campus\node_modules\react-markdown\package.json.

### Runtime

Node v12

### Package manager

npm v6

### OS

Windows

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
This package is ESM only. More information can be found in the first paragraph of the Install section: https://github.com/remarkjs/react-markdown#install

**Comment by pnkapadia64** [comment]
@wooorm I'm facing the same issue with plugin `'remark-external-links'`
```
import remarkExternalLinks from 'remark-external-links';
import ReactMarkdown from 'react-markdown';

<ReactMarkdown linkTarget="_blank" plugins={[remarkExternalLinks]}>
          Some Text
</ReactMarkdown>
```

```
react-markdown - 7.1.1
remark-external-links - 9.0.1
```

Error:
```
error - unhandledRejection: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /xyz/node_modules/react-markdown/index.js
require() of ES modules is not supported.
require() of /xyz/node_modules/react-markdown/index.js from /xyz/.next/server/pages/privacy-policy-inline.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /xyz/node_modules/react-markdown/package.json.

    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Object.require.extensions.<computed> [as .js] (/xyz/node_modules/ts-node/src/index.ts:851:44)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.react-markdown (/xyz/.next/server/pages/privacy-policy-inline.js:3257:18)
    at __webpack_require__ (/xyz/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/privacy-policy.tsx:9:72)
    at Function.__webpack_require__.a (/xyz/.next/server/webpack-runtime.js:106:13) {
  code: 'ERR_REQUIRE_ESM',
  page: '/privacy-policy'
}
```

**Comment by ChristianMurphy** [comment]
@pnkapadia64 sorry you ran into a spot of trouble.
Take a look at https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c it introduces how to use ESM with a number of build systems

From the logs it looks like you are running Next.js if so, either upgrade to 11.1 and enable ESM support as documented here https://nextjs.org/blog/next-11-1#es-modules-support, or upgrade to Next 12 which enables ESM by default https://nextjs.org/blog/next-12#es-modules-support-and-url-imports

**Comment by AhmedBHameed** [comment]
I'm getting the same error even with next.js 12 ??

Any suggestions?

**Comment by JounQin** [comment]
@AhmedBHameed You must  provide a minimal but runnable reproduction if you think it is unexpected. But it should be a usage question mostly.

**Comment by AhmedBHameed** [comment]
@JounQin 

Sorry for my laziness here. However, here is a reproduceing

https://codesandbox.io/s/nextjs-esm-error-e13sh3?file=/pages/index.js

I'm open for any suggestion.

**Comment by JounQin** [comment]
@AhmedBHameed I didn't look through in details, but you didn't follow https://github.com/remarkjs/react-markdown/issues/649#issuecomment-987443828 at least.

https://nextjs.org/blog/next-11-1#es-modules-support 

```js
// next.config.js
module.exports = {
  // Prefer loading of ES Modules over CommonJS
  experimental: { esmExternals: true },
};
```

**Comment by AhmedBHameed** [comment]
@JounQin 
A fact here that my project is using typescript.
As soon i set `type: "module"` in `package.json`, I get this error now

```ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /home/ahmed/Desktop/www/rocketdev.dev/server/index.ts
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
error Command failed with exit code 1.
```

I'm also using custom server which is using custom tsconfig.

**tsconfig.json**

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

**tsconfig.server.json**

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "noEmit": false,
    "target": "ES2015",
    "moduleResolution": "node",
    "outDir": ".next/server"
  },
  "include": ["server"]
}
```

**package.json**

```json
{
  "private": true,
  "scripts": {
    "dev": "ts-node --project tsconfig.server.json server/index.ts",
    "type-check": "tsc",
    "codegen": "graphql-codegen --config codegen.yml",
    "build:next": "next build",
    "build:server": "tsc --project tsconfig.server.json",
    "build": "npm run build:next && NODE_ENV=production npm run build:server",
    "start": "NODE_ENV=production node .next/server/server/index.js",
    "postinstall": "node ./scripts/copy_assets_to_public.js"
  },
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@apollo/gateway": "^2.0.5",
    "@apollo/utils.keyvaluecache": "^1.0.1",
    "@graphql-codegen/cli": "^2.11.5",
    "@graphql-codegen/introspection": "^2.2.1",
    "@graphql-codegen/typescript": "^2.7.3",
    "@graphql-codegen/typescript-operations": "^2.5.3",
    "@graphql-codegen/typescript-react-apollo": "^3.3.3",
    "@headlessui/react": "^1.6.6",
    "@heroicons/react": "^1.0.6",
    "@hookform/resolvers": "^2.9.7",
    "@tailwindcss/typography": "^0.5.4",
    "apollo-server-core": "^3.10.0",
    "apollo-server-express": "^3.10.0",
    "axios": "^0.27.2",
    "cookie-parser": "^1.4.6",
    "cors": "^2.8.5",
    "emoji-dictionary": "^1.0.11",
    "express": "^4.18.1",
    "graphql": "^16.5.0",
    "helmet": "^5.1.1",
    "immutability-helper": "^3.1.1",
    "joi": "^17.6.0",
    "lodash": "^4.17.21",
    "markdown-to-jsx": "^7.1.7",
    "next": "^12.2.4",
    "next-i18next": "^11.3.0",
    "next-themes": "^0.2.0",
    "parse-numeric-range": "^1.3.0",
    "prism-react-renderer": "^1.3.5",
    "react": "^18.2.0",
    "react-dnd": "^16.0.1",
    "react-dnd-html5-backend": "^16.0.1",
    "react-dom": "^18.2.0",
    "react-feather": "^2.0.10",
    "react-hook-form": "^7.34.0",
    "react-json-view": "^1.21.3",
    "react-markdown": "6.0.0",
    "react-paginate": "^8.1.3",
    "react-syntax-highlighter": "^15.5.0",
    "react-toastify": "^9.0.8",
    "sanitize-html": "^2.7.1",
    "ulid": "^2.3.0",
    "winston": "^3.8.1",
    "winston-transport": "^4.5.0"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^4.1.3",
    "@types/cookie-parser": "^1.4.3",
    "@types/cors": "^2.8.12",
    "@types/express": "^4.17.13",
    "@types/lodash": "^4.14.182",
    "@types/node": "^18.6.5",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "@types/react-syntax-highlighter": "^15.5.4",
    "autoprefixer": "^10.4.8",
    "postcss": "^8.4.16",
    "postcss-preset-env": "^7.7.2",
    "prettier": "^2.7.1",
    "tailwindcss": "^3.1.8",
    "ts-node": "^10.9.1",
    "typescript": "4.7"
  },
  "type": "module"
}
```

I will check `ts-node` since this thread I found here https://stackoverflow.com/questions/63445821/ts-node-execute-typescript-with-module-import-and-module-defined

**Comment by JounQin** [comment]
@AhmedBHameed See https://github.com/TypeStrong/ts-node#err_unknown_file_extension

In short, use `ts-node-esm` instead.

**Comment by JounQin** [comment]
I'll stop commenting, it's very out of scope now.

**Comment by AhmedBHameed** [comment]
Yes I agree. That is why I started to look my self.
However, thanks a lot for your kind support.
