### ISSUE TITLE
An error occurred during route handling or page rendering. TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by Shashank3736** [remarkjs/react-markdown#730]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

deno fresh

### Steps to reproduce

```ts
import ReactMarkdown from 'https://esm.sh/react-markdown@7';

export default function About() {
    return (
        <>
        <div className="p-4 mx-auto max-w-screen-md">
            <h1 className="text-center font-bold">About</h1>
            <br />
            <ReactMarkdown>{`
            # About
        )`}</ReactMarkdown>
        </div>
        </>
    );
}
``` JUst use this code in deno fresh framework.

### Expected behavior

Showed
# About

### Actual behavior

```
An error occurred during route handling or page rendering.

TypeError: Cannot convert a Symbol value to a string
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1829)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:2578)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at E (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:1729)
    at q (https://esm.sh/v106/preact-render-to-string@5.2.4/X-ZS8q/deno/preact-render-to-string.js:12:316)```

### Runtime

Deno

### Package manager

pnpm, Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
The markdown in your question is broken

**Comment by wooorm** [comment]
`react-markdown` uses React. You use Preact. That isn’t going to work together normally.

You probably don’t need this project. Use something like `micromark` or `remark` instead to turn markdown into HTML and send that.

Or use MDX.

Or configure [`esm.sh`](https://esm.sh/) to alias React to preact instead.

**Comment by Tims777** [comment]
@Shashank3736 Preact provides a compatibility layer which should behave just the same way as conventional React does.

Add this to your `import_map.json`:
```
"preact-markdown": "https://esm.sh/react-markdown@7.1.2?alias=react:preact/compat"
```

Then, in your `About.tsx` you can write:
```
import PreactMarkdown from "preact-markdown";

export default function About() {
  return (
    <>
      <div className="p-4 mx-auto max-w-screen-md">
        <PreactMarkdown>
          # About
        </PreactMarkdown>
      </div>
    </>
  );
}
```
